---
# Generic configuration for Lamia.
version: 0.1

lamia:
    # This should be defined if monitoring host is available
    monitoring:
        host: na58-dev
        port: 8088
        api: v0
    backends:
        HTCondor:
            nRestartRetries: 3
            minStatusUpdateTimeSec: 30
...
